name: SolarDesignTool
favicon: null
layout_spectrum: 0.9769495278596878
typography_spectrum: 0.5250504158902913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.734076596563682
  lightness: 0.4233770302962512
  saturation: 0.5695774673949927
  rhythmicContrast: 0.37017774768173695
purpose: []
